/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logistirio;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kmanolatos
 */
public class CustomerDebtByYear extends javax.swing.JFrame {

    DBExecution execute = new DBExecution();
    DefaultTableModel tableModel;
    Vector row;
    ArrayList<CustomerDeptModel> debtModel;
    ArrayList<CustomerModel> model;
    CustomerModel customerModel;
    NumberFormat numberFormatter = new DecimalFormat("###,###.##");

    /**
     * Creates new form CustomerDebtAnalytical
     */
    public CustomerDebtByYear(ArrayList<CustomerModel> model, CustomerModel customerModel) {
        this.model = model;
        this.customerModel = customerModel;
        initComponents();
    }

    private CustomerDebtByYear() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerDebtScrollPane = new javax.swing.JScrollPane();
        customerDebtTable = new javax.swing.JTable();
        backArrowLabel = new javax.swing.JLabel();
        yearScrollPane = new javax.swing.JScrollPane();
        yearComboBox = new javax.swing.JComboBox<>();
        deleteDebtYearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ανάλυση Οφειλών Ανά Έτος");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        customerDebtTable.setBackground(new java.awt.Color(204, 204, 204));
        customerDebtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        customerDebtScrollPane.setViewportView(customerDebtTable);

        getContentPane().add(customerDebtScrollPane);
        customerDebtScrollPane.setBounds(130, 10, 452, 402);

        backArrowLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backArrowLabelMouseReleased(evt);
            }
        });
        getContentPane().add(backArrowLabel);
        backArrowLabel.setBounds(610, 180, 90, 40);

        yearScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        yearScrollPane.setBorder(null);
        yearScrollPane.setOpaque(false);

        yearComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yearComboBox.setMaximumRowCount(4);
        yearComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearComboBoxItemStateChanged(evt);
            }
        });
        yearScrollPane.setViewportView(yearComboBox);

        getContentPane().add(yearScrollPane);
        yearScrollPane.setBounds(590, 350, 110, 80);

        deleteDebtYearButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteDebtYearButton.setText("Διαγραφή");
        deleteDebtYearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteDebtYearButtonMouseReleased(evt);
            }
        });
        getContentPane().add(deleteDebtYearButton);
        deleteDebtYearButton.setBounds(590, 160, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getContentPane().setBackground(Color.GRAY);
        try {
            customerDebtScrollPane.setVisible(false);
            yearScrollPane.setVisible(false);
            backArrowLabel.setVisible(false);
            deleteDebtYearButton.setVisible(false);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int w = (int) screenSize.getWidth();
            int h = (int) screenSize.getHeight();
            setSize(w * 90 / 100, h * 83 / 100);
            setLocationRelativeTo(null);
            BufferedImage img = null;
            setLocationRelativeTo(null);
            URL urlToImage = getClass().getResource("/img/backArrow.png");
            try {
                img = ImageIO.read(urlToImage);
            } catch (IOException e) {
                e.printStackTrace();
            }
            Image dimg = img.getScaledInstance(w * 4 / 100, h * 2 / 100, Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            backArrowLabel.setIcon(imageIcon);
            backArrowLabel.setLocation(w * 3 / 100, h * 3 / 100);
            backArrowLabel.setSize(w * 4 / 100, h * 2 / 100);
            yearScrollPane.setLocation(w * 34 / 100, h * 2 / 100);
            yearScrollPane.setSize(w * 10 / 100, h * 4 / 100);
            Font currentFont = deleteDebtYearButton.getFont();
            deleteDebtYearButton.setFont(currentFont.deriveFont(Font.BOLD, w * 1 / 100));
            deleteDebtYearButton.setLocation(w * 49 / 100, h * 2 / 100);
            deleteDebtYearButton.setSize(w * 10 / 100, h * 4 / 100);
            yearScrollPane.getViewport().setOpaque(false);
            DefaultListCellRenderer dlcr = new DefaultListCellRenderer();
            dlcr.setHorizontalAlignment(DefaultListCellRenderer.CENTER);
            yearComboBox.setRenderer(dlcr);
            tableModel = (DefaultTableModel) customerDebtTable.getModel();
            tableModel.addColumn("Επώνυμο");
            tableModel.addColumn("Όνομα");
            tableModel.addColumn("Αιτιολογία");
            tableModel.addColumn("Χρέος");
            tableModel.addColumn("Πίστωση");
            tableModel.addColumn("Υπόλοιπο");
            tableModel.addColumn("Ημερομηνία");
            customerDebtTable.setRowHeight(h * 5 / 100);
            customerDebtTable.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 18));
            customerDebtTable.setShowGrid(true);
            customerDebtScrollPane.setLocation(w * 1 / 100, h * 13 / 100);
            customerDebtScrollPane.setSize(w * 88 / 100, h * 65 / 100);
            ArrayList<Integer> yearList = new ArrayList<Integer>();
            int i, j;
            int maxYear = execute.GetMaxYear(customerModel.id);
            debtModel = execute.SelectCustomersDebtByYear("select date, reason, xreosi, pistosi, ipolipo, debtYear from customersDebtByYear where id = " + customerModel.id);
            for (CustomerDeptModel item : debtModel) {
                if (yearList.size() == 0) {
                    deleteDebtYearButton.setVisible(true);
                    yearList.add(item.year);
                } else {
                    for (i = 0; i < yearList.size(); i++) {
                        if (yearList.get(i) == item.year) {
                            break;
                        } else {
                            if (yearList.get(yearList.size() - 1) == item.year) {
                                break;
                            } else {
                                yearList.add(item.year);
                            }
                        }
                    }
                }
                if (item.year == maxYear) {
                    row = new Vector();
                    row.add(customerModel.customerSurname);
                    row.add(customerModel.customerName);
                    row.add(item.reason);
                    row.add(numberFormatter.format(item.xreosi));
                    row.add(numberFormatter.format(item.pistosi));
                    row.add(numberFormatter.format(item.ipolipo));
                    row.add(item.date);
                    tableModel.addRow(row);
                }
            }
            for (i = 0; i < yearList.size(); ++i) {
                for (j = i + 1; j < yearList.size(); ++j) {
                    if (yearList.get(i) < yearList.get(j)) {
                        int temp = yearList.get(i);
                        yearList.set(i, yearList.get(j));
                        yearList.set(j, temp);
                    }
                }
            }
            for (i = 0; i < yearList.size(); ++i) {
                yearComboBox.addItem(String.valueOf(yearList.get(i)));
            }
            if (yearComboBox.getItemCount() > 0) {
                yearScrollPane.setVisible(true);
            }
            customerDebtScrollPane.setVisible(true);
            backArrowLabel.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerDebtAnalytical.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerDebtAnalytical.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void backArrowLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowLabelMouseReleased
        new SearchCustomer(model).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backArrowLabelMouseReleased

    private void yearComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearComboBoxItemStateChanged
        try {
            if (evt.getStateChange() == ItemEvent.DESELECTED) {
                tableModel.setRowCount(0);
                debtModel = execute.SelectCustomersDebtByYear("select date, reason, xreosi, pistosi, ipolipo, debtYear from customersDebtByYear where id = " + customerModel.id + " and debtYear = " + yearComboBox.getSelectedItem());
                for (CustomerDeptModel item : debtModel) {
                    row = new Vector();
                    row.add(customerModel.customerSurname);
                    row.add(customerModel.customerName);
                    row.add(item.reason);
                    row.add(numberFormatter.format(item.xreosi));
                    row.add(numberFormatter.format(item.pistosi));
                    row.add(numberFormatter.format(item.ipolipo));
                    row.add(item.date);
                    tableModel.addRow(row);
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerDebtByYear.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerDebtByYear.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yearComboBoxItemStateChanged

    private void deleteDebtYearButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDebtYearButtonMouseReleased
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Είστε σίγουρος πως θέλετε να διαγράψετε την ανάλυση οφειλών του έτους " + yearComboBox.getSelectedItem() + "?", "Επιβεβαίωση", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                execute.UpsertOrDelete("delete from customersDebtByYear where id = " + customerModel.id + " and debtYear = " + yearComboBox.getSelectedItem());
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this,
                        "Η διαγραφή απέτυχε!",
                        "Σφάλμα",
                        JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,
                        "Η διαγραφή απέτυχε!",
                        "Σφάλμα",
                        JOptionPane.ERROR_MESSAGE);
            }
            yearComboBox.removeItemAt(yearComboBox.getSelectedIndex());
            if (yearComboBox.getItemCount() == 0) {
                yearScrollPane.setVisible(false);
                deleteDebtYearButton.setVisible(false);
            }
            JOptionPane.showMessageDialog(this,
                    "Η διαγραφή έγινε με επιτυχία!");
        }
    }//GEN-LAST:event_deleteDebtYearButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDebtByYear.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDebtByYear.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDebtByYear.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDebtByYear.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDebtByYear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backArrowLabel;
    private javax.swing.JScrollPane customerDebtScrollPane;
    private javax.swing.JTable customerDebtTable;
    private javax.swing.JButton deleteDebtYearButton;
    private javax.swing.JComboBox<String> yearComboBox;
    private javax.swing.JScrollPane yearScrollPane;
    // End of variables declaration//GEN-END:variables
}
