/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logistirio;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kmanolatos
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phoneLabel = new javax.swing.JLabel();
        keyLabel = new javax.swing.JLabel();
        keyText = new javax.swing.JTextField();
        phoneText = new javax.swing.JTextField();
        retrievePassButton = new javax.swing.JButton();
        backArrowLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Υπενθύμιση Κωδικού");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        phoneLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phoneLabel.setText("Αριθμός Τηλεφώνου :");
        getContentPane().add(phoneLabel);
        phoneLabel.setBounds(20, 40, 290, 60);

        keyLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        keyLabel.setText("Λέξη - Κλειδί :");
        getContentPane().add(keyLabel);
        keyLabel.setBounds(220, 200, 170, 30);
        getContentPane().add(keyText);
        keyText.setBounds(380, 130, 130, 20);
        getContentPane().add(phoneText);
        phoneText.setBounds(370, 50, 130, 20);

        retrievePassButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        retrievePassButton.setText("Υπενθύμιση");
        retrievePassButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                retrievePassButtonMouseReleased(evt);
            }
        });
        getContentPane().add(retrievePassButton);
        retrievePassButton.setBounds(40, 200, 140, 30);

        backArrowLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backArrowLabelMouseReleased(evt);
            }
        });
        getContentPane().add(backArrowLabel);
        backArrowLabel.setBounds(360, 20, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getContentPane().setBackground(Color.GRAY);
        phoneLabel.setVisible(false);
        phoneText.setVisible(false);
        keyLabel.setVisible(false);
        keyText.setVisible(false);
        retrievePassButton.setVisible(false);
        backArrowLabel.setVisible(false);
        BufferedImage img = null;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int w = (int) screenSize.getWidth();
        int h = (int) screenSize.getHeight();
        setSize(w * 50 / 100, h * 49 / 100);
        setLocationRelativeTo(null);
        URL urlToImage = getClass().getResource("/img/backArrow.png");
        try {
            img = ImageIO.read(urlToImage);
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(w * 4 / 100, h * 2 / 100, Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        backArrowLabel.setIcon(imageIcon);
        backArrowLabel.setLocation(w * 3 / 100, h * 3 / 100);
        backArrowLabel.setSize(w * 4 / 100, h * 2 / 100);
        Font currentFont = phoneLabel.getFont();
        phoneLabel.setFont(currentFont.deriveFont(Font.BOLD, w * 2 / 100));
        phoneLabel.setSize(w * 50 / 100, h * 5 / 100);
        phoneLabel.setLocation(w * 14 / 100, h * 8 / 100);
        phoneText.setLocation(w * 14 / 100, h * 14 / 100);
        phoneText.setSize(w * 12 / 100, h * 4 / 100);
        phoneText.setFont(currentFont.deriveFont(Font.PLAIN, w * 1.7F / 100));
        keyLabel.setFont(currentFont.deriveFont(Font.BOLD, w * 2 / 100));
        keyLabel.setSize(w * 50 / 100, h * 5 / 100);
        keyLabel.setLocation(w * 14 / 100, h * 20 / 100);
        keyText.setLocation(w * 14 / 100, h * 25 / 100);
        keyText.setSize(w * 12 / 100, h * 4 / 100);
        keyText.setFont(currentFont.deriveFont(Font.PLAIN, w * 1.7F / 100));
        retrievePassButton.setFont(currentFont.deriveFont(Font.BOLD, w * 1 / 100));
        retrievePassButton.setLocation(w * 12 / 100, h * 34 / 100);
        retrievePassButton.setSize(w * 16 / 100, h * 5 / 100);
        phoneLabel.setVisible(true);
        phoneText.setVisible(true);
        keyLabel.setVisible(true);
        keyText.setVisible(true);
        retrievePassButton.setVisible(true);
        backArrowLabel.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void retrievePassButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrievePassButtonMouseReleased
        try {
            DBExecution select = new DBExecution();
            AdminModel model = select.GetAdminPass();
            if (phoneText.getText().equals(model.phoneNumber) || keyText.getText().equals(model.key)) {
                JOptionPane.showMessageDialog(this,
                        "Username : " + model.user + "\nPassword : " + model.pass);
                new Login().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Ο Αριθμός Τηλεφώνου ή η Λέξη - Κλειδί είναι λάθος!",
                        "Σφάλμα",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_retrievePassButtonMouseReleased

    private void backArrowLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowLabelMouseReleased
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backArrowLabelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backArrowLabel;
    private javax.swing.JLabel keyLabel;
    private javax.swing.JTextField keyText;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneText;
    private javax.swing.JButton retrievePassButton;
    // End of variables declaration//GEN-END:variables
}
